version: "3.8"
services:
  db:
    image: docker.io/supabase/postgres:15.1.0.103
    ports:
      - "5432:5432"
    env_file:
      - .env.local

  studio:
    image: docker.io/supabase/studio:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - db